#! usr/bin/env python3

#Food At Home
#Your virtual kitchen inventory and shopping list generator

#See My Kitchen function
def seeMyKitchen():
  print("Hello from your kitchen!")

####################### START HERE #########################
#Main Module
def main():
    print("Welcome to Food At Home!") 
    print("Your kitchen inventory and shopping list generator in your hand.")
    firstContact = userinput("Please type in what you'd like to do today:")
    #list of user actions to select from
    userActions = ["See My Kitchen", "Import A Grocery Reciept"]
    userActions.islower()
    if firstContact == "see my kitchen":
        seeMyKitchen()
    else:
        print("Please selection a valid option.")
        main() 


        
#Kitchen Inventory
#fooditem = input("Add new food item: ")

#Stock options for kitchen inventory
#itemAmount = input("Please input how much you have (Please select Full, Low, or Empty):")
#if itemAmount == "Full":
#    print("Full Stock")
#elif itemAmount == "Low":
#   print("Low Stock")
#elif itemAmount == "Empty":
#   itemAmount == "Out of Stock"
#
#Shopping List
#if (itemAmount == "Out of Stock") or (itemAmount == "Low Stock"):
#    print(fooditem)
#else:
#   print("Your kitchen is fully stocked!") 
