#! usr/bin/env python3

#Food At Home
#Your virtual kitchen inventory and shopping list generator

#kitchen Inventory list
kitchenInventory = []

#See My Kitchen function
def seeMyKitchen():
  print("\nWelcome to your virtual kitchen!")
  print("Here is your current inventory:")
  if len(kitchenInventory) == 0:
      print("\nUh oh! It looks like your kitchen doesn't have any food. Let's fix that.")
      
  else:
      print(kitchenInventory)

####################### START HERE #########################
#Main Module
def main():
    print("Welcome to Food At Home!") 
    print("Your kitchen inventory and shopping list generator in your hand.")

    #list of user actions
    userActions = ["1. See My Kitchen", "2. Import A Grocery Reciept"]
    print("\nList of Actions:")
    print(*userActions, sep="\n")

    #prompt for first user input 
    firstContact = input("\nPlease type the list number of what you'd like to do today:")

    #list of user actions to select from
    if firstContact == "1":
        seeMyKitchen()
    else:
        print("Please selection a valid option.")
        main()

# call the main function
if __name__ == "__main__":
    main()

#Add food
def addFood():
    fooditem = input("Add new item: ")

#Set food stock
#Stock options for kitchen inventory
#itemAmount = input("Please input how much you have (Please select Full, Low, or Empty):")
#if itemAmount == "Full":
#    print("Full Stock")
#elif itemAmount == "Low":
#   print("Low Stock")
#elif itemAmount == "Empty":
#   itemAmount == "Out of Stock"
#
#Shopping List
#if (itemAmount == "Out of Stock") or (itemAmount == "Low Stock"):
#    print(fooditem)
#else:
#   print("Your kitchen is fully stocked!") 
